#!/bin/bash

cd "${0%/*}"

terraform output -json ip_addresses  | python3 -c '
data = eval(input())
for port in range(11211, 11211 + 4):
    for server in data:
        print("-d {}:{}".format(server, port), end=" ")
print()'
